"""Add CandleData model for stock candles

Revision ID: 0add1d368ce0
Revises: 387407bf2c74
Create Date: 2025-09-19 14:12:06.364357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0add1d368ce0'
down_revision = '387407bf2c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candle_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('timestamp_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'interval', 'timestamp_start', name='uq_candle_data_stock_interval_start')
    )
    with op.batch_alter_table('candle_data', schema=None) as batch_op:
        batch_op.create_index('ix_candle_data_stock_interval_start', ['stock_id', 'interval', 'timestamp_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candle_data', schema=None) as batch_op:
        batch_op.drop_index('ix_candle_data_stock_interval_start')

    op.drop_table('candle_data')
    # ### end Alembic commands ###
